/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF, Float } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const ref = useRef();
  const ref1 = useRef();
  const ref2 = useRef();
  const ref3 = useRef();
  const ref4 = useRef();
  const ref5 = useRef();
  const group = useRef();
  const { nodes, materials } = useGLTF('/Logo.glb');
  const [hover, setHover] = useState(false)

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    // ref.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20
    // ref.current.rotation.x = Math.cos(t / 4) / 8
    // ref.current.rotation.y = Math.sin(t / 4) / 8
    ref.current.position.y = (1 - Math.sin(t / 0.6)) / 30
    ref1.current.position.y = (1 - Math.sin(t / 0.6)) / 8
    ref2.current.position.y = (1 + Math.sin(t / 0.6)) / 10
    ref2.current.position.y = (1 + Math.sin(t / 0.6)) / 20
    ref3.current.position.y = (1 - Math.sin(t / 0.6)) / 30
    ref4.current.position.y = (1 + Math.sin(t / 0.6)) / 20
    ref5.current.position.y = (1 - Math.sin(t / 0.6)) / 10
  })

  return (
    <group ref={group} {...props} dispose={null} position={[1.25, -1.5, 0]} scale={0.8} rotation={[0, 3, 0]}>
        <mesh
          ref={ref}
          geometry={nodes.Curve.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={25.45} />
        <mesh 
          onPointerOver={() => setHover(true)}
          onPointerOut={() => setHover(false)}
          ref={ref1}
          geometry={nodes.Curve001.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={hover ? 29 : 25.45} />
        <mesh 
          ref={ref2}
          geometry={nodes.Curve002.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={25.45} />
        <mesh
          ref={ref3}
          geometry={nodes.Curve003.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={25.45} />
        <mesh 
          ref={ref4}
          geometry={nodes.Curve004.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={25.45} />
        <mesh
          ref={ref5}
          geometry={nodes.Curve005.geometry} 
          material={materials.SVGMat} 
          position={[0, 0, 0.96]} 
          rotation={[Math.PI / 2, 0, 0]} 
          scale={25.45} />
    </group>
  )
}

useGLTF.preload('/Logo.glb')
