/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Logo.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, -1.5, 0]} scale={0.8} >
      <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
      <mesh geometry={nodes.Curve001.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
      <mesh geometry={nodes.Curve002.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
      <mesh geometry={nodes.Curve003.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
      <mesh geometry={nodes.Curve004.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
      <mesh geometry={nodes.Curve005.geometry} material={materials.SVGMat} position={[0, 0, 0.96]} rotation={[Math.PI / 2, 0, 0]} scale={25.45} />
    </group>
  )
}

useGLTF.preload('/Logo.glb')
